### ISSUE TITLE
feat/account - 전화번호 관련 로직

### ISSUE THREAD

**Issue by daeguhighman** [vietman2/BaseballTeam#19]

**Comment by vietman2** [comment]
원칙: 전화번호는 DB에 010-xxxx-yyyy 형태로만 저장한다.

세부:

- [] 010-xxxx-yyyy 의 형태로 가입이 들어오면 통과
- [] 010xxxxyyyy의 형태로 들어오면, 내부 로직을 거쳐 -를 자동으로 넣어주고 통과
- [] 나머지는 에러를 리턴한다

기타:

- [] 전화번호 인증 절차를 추가한다
- [] 단, 정승원 윤동현 등 관리자 권한의 유저들은 이 절차를 밟지 않는다 (createsuperuser를 통한 유저 생성)
