### ISSUE TITLE
feat/account - 권한 관련 로직

### ISSUE THREAD

**Issue by daeguhighman** [vietman2/BaseballTeam#22]

**Comment by vietman2** [comment]
절차: 

1. 클라이언트에서 특정 기능을 사용할 때, 해당 사용자가 권한이 있는지를 서버에 물어본다
2. 서버는 True/False (yes or no) 로 응답한다

로직 설계

- [ ] 클라이언트 측에서, 유저에 대한 정보 (pk 아니면 전번), 그리고 물어보는 범위-(주장단이냐? 활동중인 부원이냐? 등)-를 담아 요청한다
- [ ] 서버는 이를 확인하고 응답한다 (아마도 managers.py 에 로직 추가하는게 맞을듯)
